// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCalsvywIQv2U1ACLleVwJkyrRbBLisWN0',
    appId: '1:847852228766:web:53ed6300b733ea9ca4eb8f',
    messagingSenderId: '847852228766',
    projectId: 'movies-5ecba',
    authDomain: 'movies-5ecba.firebaseapp.com',
    storageBucket: 'movies-5ecba.appspot.com',
    measurementId: 'G-GZNKZR7R65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyl-tdxkqZe9J9wn8LOCXacICaSNjk5I0',
    appId: '1:847852228766:android:a0023e9fc46de9e1a4eb8f',
    messagingSenderId: '847852228766',
    projectId: 'movies-5ecba',
    storageBucket: 'movies-5ecba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzFyfk_t6tOm6KDuY-vDJ-gL-sh0rbyzM',
    appId: '1:847852228766:ios:4ab920082bbdbc43a4eb8f',
    messagingSenderId: '847852228766',
    projectId: 'movies-5ecba',
    storageBucket: 'movies-5ecba.appspot.com',
    iosBundleId: 'com.example.movies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzFyfk_t6tOm6KDuY-vDJ-gL-sh0rbyzM',
    appId: '1:847852228766:ios:b29cd4c2756c6bb8a4eb8f',
    messagingSenderId: '847852228766',
    projectId: 'movies-5ecba',
    storageBucket: 'movies-5ecba.appspot.com',
    iosBundleId: 'com.example.movies.RunnerTests',
  );
}
